# Generated by Django 5.0.1 on 2024-01-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris libero purus, convallis id ligula et, aliquam imperdiet magna. Donec nec dignissim urna. Sed laoreet quis ligula vitae convallis. Donec vel lobortis dui. Etiam leo nunc, consequat a cursus vitae, dapibus pretium nulla. Phasellus tristique nibh quis auctor blandit. Donec in pharetra sem. In efficitur ipsum in metus porta egestas. Nam enim lectus, efficitur vel nisi et, sodales commodo nisi. Nulla cursus gravida ipsum. Aenean pretium in nisl at congue.'),
        ),
    ]
